web:
  build: .
  command: lein run
  networks: app
  ports:
    - "8081:8081"
#    - "6379:6379" //bind: address already in use
  volumes:
    - ".:/mnt"
  # restart: always

redis:
#  restart: always
  networks: app
  ports:
  - 6379:6379  #端口号
  image: redis #docker 镜像
  command: redis-server /data/redis.conf
  volumes:
    - "/mnt/redis/data:/data"