version: '2.1'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: lein run
    networks:
      - app
    ports:
      - "8081:8081"
    volumes:
      - ".:/mnt"

    networks:
      default:
        ipv4_address: 172.17.0.2

  redis:
    image: redis #docker 镜像
    networks:
      default:
        ipv4_address: 172.17.0.2
    ports:
      - "6379:6379"  #端口号
    command: redis-server /data/redis.conf
    volumes:
      - "/mnt/redis/data:/data"
    # restart: always
