version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: lein run
    networks:
      - app
    ports:
      - "8081:8081"
    volumes:
      - ".:/mnt"

    networks:
      app:
        ipv4_address: 172.18.0.2

  redis:
    image: redis #docker 镜像
    networks:
      app:
        ipv4_address: 172.18.0.3
    ports:
      - "6379:6379"  #端口号
    command: redis-server /data/redis.conf
    volumes:
      - "/mnt/redis/data:/data"
    # restart: always

networks:
  app:
    external:
      name: app_name

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.1/16