services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: lein run
    networks:
      - app
    ports:
      - "8081:8081"
    volumes:
      - ".:/mnt"

  redis:
    image: redis #docker 镜像
    networks:
      - app
    ports:
      - "6379:6379"  #端口号
    command: redis-server /data/redis.conf
    volumes:
      - "/mnt/redis/data:/data"
    # restart: always

networks:
  app:
